spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database-platform: "org.hibernate.dialect.H2Dialect"
  datasource:
    url: jdbc:h2:file:./data/dabase.h2
    driverClassName: org.h2.Driver
    username: sa
    password: ""
app:
  artnet:
    outputs:
      - name: "Test Output"
        address: 192.168.2.102
        universes: [0]
